---
services:
  pma:
    container_name: pma
    image: docker.io/library/phpmyadmin:latest
    # user: 0:0
    env_file: [.env]
    environment:
      - PMA_QUERYHISTORYDB=true
      - PMA_QUERYHISTORYMAX=1000
    ports: [40123:80/tcp]
    # extra_hosts: [host.docker.internal:host-gateway]  # If running mysql on the host machine
    # volumes: []
    restart: no
