---
services:
  sqliteweb:
    container_name: sqliteweb
    # Dockerfile: https://github.com/coleifer/sqlite-web/blob/master/docker/Dockerfile
    build: {context: https://github.com/coleifer/sqlite-web.git#master:docker}
    image: sqliteweb:latest  # ghcr.io/coleifer/sqlite-web:latest has no arm64
    entrypoint: [sh, -c, 'sqlite_wsgi -H 0.0.0.0 -r "$$SQLITE_DATABASE"']
    user: 1000:1000
    # env_file: [.env]
    environment:
      SQLITE_DATABASE: /mnt/data/XXX.sqlite3
    ports: [8081:8080/tcp]
    volumes: [./data:/mnt/data:ro]
    restart: no
